name: CI
on:
  push:
    branches: [main, gh-windows-tests]
    tags-ignore: [dev]
  pull_request:
    branches: ['main', 'release-*']
defaults:
  run:
    shell: bash

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Perform all tests (debug mode) for `wasmtime`. This runs stable/beta/nightly
  # channels of Rust as well as macOS/Linux/Windows.
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      QEMU_BUILD_VERSION: 6.1.0
    strategy:
      matrix:
        include:
          - os: windows-2019
          - os: windows-2019
            target: x86_64-pc-windows-gnu
          - os: windows-latest
          - os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ./.github/actions/install-rust

    # Build and test all features
    - run: cargo run -- test .\\filetests\\filetests\\runtests\\fma.clif
      working-directory: cranelift
      env:
        RUST_BACKTRACE: 1
