name: CI
on:
  push:
    branches: [main, mingwtest]
    tags-ignore: [dev]
  pull_request:
    branches: ['main', 'release-*']
defaults:
  run:
    shell: bash


jobs:
  # Perform all tests (debug mode) for `wasmtime`. This runs stable/beta/nightly
  # channels of Rust as well as macOS/Linux/Windows.
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      QEMU_BUILD_VERSION: 6.1.0
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
          - os: windows-2019
            target: x86_64-pc-windows-gnu
          - os: windows-latest
          - os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ./.github/actions/install-rust

    # Install targets in order to build various tests throughout the repo
    - run: rustup target add ${{ matrix.target }}
    - run: echo CARGO_BUILD_TARGET=${{ matrix.target }} >> $GITHUB_ENV
      if: matrix.target != ''

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.target == ''
    - run: cl.exe /out:testfmacl.exe .\\test_fma.c
      if: matrix.target == ''
    - run: .\\testfmacl.exe
      if: matrix.target == ''

    - run: gcc.exe -o testfmagcc.exe .\\test_fma.c
      if: matrix.target == 'x86_64-pc-windows-gnu'
    - run: .\\testfmagcc.exe
      if: matrix.target == 'x86_64-pc-windows-gnu'

    - run: cargo run -- test .\\filetests\\filetests\\runtests\\fma.clif
      working-directory: cranelift
      env:
        RUST_BACKTRACE: 1
